---
repos:
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.20.0
    hooks:
      - id: markdownlint
        name: markdownlint
        description: Run markdownlint on markdown files
        entry: markdownlint-cli2
        language: node
        types: [markdown]
        additional_dependencies: ['markdownlint-cli2@0.20.0']
