tap "homebrew/bundle"
tap "homebrew/cask"

# Package Management
brew "ansible"

# Development Tools
brew "git"
brew "ripgrep"
brew "jq"
brew "wget"

# Shell
brew "zsh"

# Utilities
brew "tree"
brew "htop"

# Applications
cask "visual-studio-code"
cask "iterm2"
cask "docker"
cask "1password"

# Optional: Fonts
# tap "homebrew/cask-fonts"
# cask "font-fira-code"
