---
dependency:
  name: galaxy
  options:
    requirements-file: ../../../../collections/requirements.yml

driver:
  name: vagrant
  provider:
    name: virtualbox

platforms:
  - name: macos-test
    box: generic/macos13
    memory: 2048
    cpus: 2

provisioner:
  name: ansible
  config_options:
    defaults:
      callbacks_enabled: profile_tasks
  inventory:
    host_vars:
      macos-test:
        ansible_python_interpreter: /usr/bin/python3

verifier:
  name: ansible

lint: |
  set -e
  yamllint .
  ansible-lint
