---
dependency:
  name: galaxy
  options:
    requirements-file: ../../collections/requirements.yml

driver:
  name: default

platforms:
  - name: localhost

provisioner:
  name: ansible
  config_options:
    defaults:
      callbacks_enabled: profile_tasks,timer
  inventory:
    hosts:
      local:
        hosts:
          localhost:
            ansible_connection: local
            ansible_python_interpreter: /usr/bin/python3

verifier:
  name: ansible

lint: |
  set -e
  yamllint .
  ansible-lint
